apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx

spec:
  containers:
    - name: load-balancer
      image: nginx
      ports:
        - containerPort: 80
    
    - name: app-client
      image: frienemie-server
      ports:
        - containerPort: 5173